name: on-commit
on:
  push:
    paths:
      - 'action.yml'
      - 'cl.sh'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  bump_tag:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      # GitHub Action: https://github.com/marketplace/actions/github-tag-bump
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        DEFAULT_BRANCH: main
        WITH_V: false
 
  changelog:
    needs: bump_tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Changelog
      uses: MACH2Simulations/QuackBot_Docs@2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add 'content/docs/CHANGELOG.md'
        git commit -m "chore: :robot: changelog file generated" || echo "No changes to commit"
        git push
